"""Init

Revision ID: 2c8326898dec
Revises: 
Create Date: 2022-09-12 15:15:48.379697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8326898dec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录编号'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='角色名'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认角色'),
    sa.Column('permissions', sa.Integer(), nullable=True, comment='权限值'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('owner', sa.String(length=64), nullable=False, comment='所有者(工号或昵称)'),
    sa.Column('access_key', sa.String(length=32), nullable=False, comment='公钥'),
    sa.Column('secret_key', sa.String(length=32), nullable=False, comment='私钥'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否已启用'),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_user')
    op.drop_table('role')
    # ### end Alembic commands ###
